# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-24 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designer',
            name='user',
        ),
    ]
